### ISSUE TITLE
zsh shell isn't available in tsu mode in Termux

### ISSUE THREAD

**Issue by 4eckdat** [cswl/tsu#56]
![Screenshot_20200508-075824_Termux](https://user-images.githubusercontent.com/64999742/81365574-f1720e00-9101-11ea-926f-e0e6547d23f7.jpg)
Latest updates caused an issue.
After gettin' in tsu mode the output of the commands looks like this:
echo $0
/data/.../com.termux/files/usr/bin/zsh

echo $SHELL
/system/bin/sh

The problem is that the zsh can't be used, so zsh history and syntax highlightin' are not available, although it worked in previous versions.

**Comment by cswl** [comment]
Which version of Android are you using?

**Comment by 4eckdat** [comment]
Concernin' to Android 9, Magisk - 2aede977(20407), Termux 0.64

**Comment by cswl** [comment]
Oh Youre using Magisk canary.. I forgot to add check for that..
```
curl -L "https://raw.githubusercontent.com/cswl/tsu/next/shell/tsu.sh"  > "$PREFIX/bin/tsu" 
```

Please try this for the time being

**Comment by 4eckdat** [comment]
Downloaded the linked version - the same than' is still bein'.

**Comment by cswl** [comment]
> Downloaded the linked version - the same than' on the shell is still bein'.
> But "Cannot link executable" issue that was on Pie x86_64 with one of simlinked libs disappeared.

Please try this version..

The new command to debug is `tsu --dbg`
```
curl -L "https://raw.githubusercontent.com/cswl/tsu/next/dist/tsu"  > "$PREFIX/bin/tsu"
```

**Comment by cswl** [comment]
Fixed in v8.3.2 update.

Now available with `pkg install tsu`

**Comment by 4eckdat** [comment]
I am grateful for your work and response, but the situation is still the same as I described in my last post.

**Comment by cswl** [comment]
Ah, sorry.. most other issues relating to this got fixed..

Can you do a `tsu --dbg` and post the output here..

**Comment by 4eckdat** [comment]
The debug output on last version:

```
+ shift

+ TERMUX_FS=/data/data/com.termux/files

+ TERMUX_PREFIX=/data/data/com.termux/files/usr

+ TERMUX_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

+ ROOT_HOME=/data/data/com.termux/files/home/.suroot

+ ANDROIDSYSTEM_PATHS=/system/bin:/system/xbin

+ BB_MAGISK=/sbin/.magisk/busybox

+ log_DEBUG TSU_AS_SUDO

+ [[ '' == true ]]

+ log_DEBUG _TSU_AS_SUDO

+ [[ -z '' ]]

+ SWITCH_USER=

+ declare -A EXP_ENV

+ log_DEBUG _TSU_AS_SUDO

+ [[ '' == true ]]

+ root_shell_helper

+ log_DEBUG root_shell_helper

+ log_DEBUG ALT_SHELL

+ [[ '' == \s\y\s\t\e\m ]]

+ [[ -n '' ]]

+ [[ -x /data/data/com.termux/files/home/.termux/shell ]]

++ readlink -f -- /data/data/com.termux/files/home/.termux/shell

+ ROOT_SHELL=/data/sdext2/com.termux/files/usr/bin/zsh

+ env_path_helper
+ log_DEBUG env_path_helper

+ log_DEBUG SWITCH_USER

+ [[ -z '' ]]

+ NEW_HOME=/data/data/com.termux/files/home/.suroot

+ EXP_ENV[PREFIX]=/data/data/com.termux/files/usr

+ EXP_ENV[TMPDIR]=/data/data/com.termux/files/home/.suroot/.tmp

+ EXP_ENV[LD_PRELOAD]=/data/data/com.termux/files/usr/lib/libtermux-exec.so

+ log_DEBUG _TSU_AS_SUDO

+ [[ '' == true ]]

+ NEW_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

+ ASP=/system/bin:/system/xbin

+ log_DEBUG PREPEND_SYSTEM_PATH

+ [[ -n '' ]]

+ log_DEBUG APPEND_SYSTEM_PATH

+ [[ -n '' ]]

+ log_DEBUG LD_LIBRARY_PATH

+ [[ -n /data/data/com.termux/files/usr/lib ]]

+ SYS_LIBS=/system/lib64

+ EXP_ENV[LD_LIBRARY_PATH]=/data/data/com.termux/files/usr/lib:/system/lib64

+ EXP_ENV[PATH]=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

+ EXP_ENV[HOME]=/data/data/com.termux/files/home/.suroot

+ EXP_ENV[TERM]=xterm-256color

+ [[ -z true ]]

+ set +x

+ [[ -d /data/data/com.termux/files/home/.suroot ]]

+ STARTUP_SCRIPT=/data/sdext2/com.termux/files/usr/bin/zsh

+ SU_BINARY_SEARCH=("/system/xbin/su" "/system/bin/su")

+ [[ -x /sbin ]]
+ SU_BINARY_SEARCH+=("/sbin/su" "/sbin/bin/su")

+ unset LD_LIBRARY_PATH

+ unset LD_PRELOAD

+ [[ -z '' ]]

++ /sbin/su -v

+ [[ 2aede977:MAGISKSU == *\M\A\G\I\S\K\S\U ]]

+ exec /sbin/su -c 'PATH=/sbin/.magisk/busybox env -i  PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets  LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib:/system/lib64  ANDROID_DATA=/data  TMPDIR=/data/data/com.termux/files/home/.suroot/.tmp  PREFIX=/data/data/com.termux/files/usr  TERM=xterm-256color  LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so  ANDROID_ROOT=/system  HOME=/data/data/com.termux/files/home/.suroot  /data/sdext2/com.termux/files/usr/bin/zsh'

```

**Comment by 4eckdat** [comment]
`+ shift

+ TERMUX_FS=/data/data/com.termux/files

+ TERMUX_PREFIX=/data/data/com.termux/files/usr

+ TERMUX_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

+ ROOT_HOME=/data/data/com.termux/files/home/.suroot

+ ANDROIDSYSTEM_PATHS=/system/bin:/system/xbin

+ BB_MAGISK=/sbin/.magisk/busybox

+ log_DEBUG TSU_AS_SUDO

+ [[ '' == true ]]

+ log_DEBUG _TSU_AS_SUDO

+ [[ -z '' ]]

+ SWITCH_USER=

+ declare -A EXP_ENV

+ log_DEBUG _TSU_AS_SUDO

+ [[ '' == true ]]

+ root_shell_helper

+ log_DEBUG root_shell_helper

+ log_DEBUG ALT_SHELL

+ [[ '' == \s\y\s\t\e\m ]]

+ [[ -n '' ]]

+ [[ -x /data/data/com.termux/files/home/.termux/shell ]]

++ readlink -f -- /data/data/com.termux/files/home/.termux/shell

+ ROOT_SHELL=/data/sdext2/com.termux/files/usr/bin/zsh

+ env_path_helper
+ log_DEBUG env_path_helper

+ log_DEBUG SWITCH_USER

+ [[ -z '' ]]

+ NEW_HOME=/data/data/com.termux/files/home/.suroot

+ EXP_ENV[PREFIX]=/data/data/com.termux/files/usr

+ EXP_ENV[TMPDIR]=/data/data/com.termux/files/home/.suroot/.tmp

+ EXP_ENV[LD_PRELOAD]=/data/data/com.termux/files/usr/lib/libtermux-exec.so

+ log_DEBUG _TSU_AS_SUDO

+ [[ '' == true ]]

+ NEW_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

+ ASP=/system/bin:/system/xbin

+ log_DEBUG PREPEND_SYSTEM_PATH

+ [[ -n '' ]]

+ log_DEBUG APPEND_SYSTEM_PATH

+ [[ -n '' ]]

+ log_DEBUG LD_LIBRARY_PATH

+ [[ -n /data/data/com.termux/files/usr/lib ]]

+ SYS_LIBS=/system/lib64

+ EXP_ENV[LD_LIBRARY_PATH]=/data/data/com.termux/files/usr/lib:/system/lib64

+ EXP_ENV[PATH]=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

+ EXP_ENV[HOME]=/data/data/com.termux/files/home/.suroot

+ EXP_ENV[TERM]=xterm-256color

+ [[ -z true ]]

+ set +x

+ [[ -d /data/data/com.termux/files/home/.suroot ]]

+ STARTUP_SCRIPT=/data/sdext2/com.termux/files/usr/bin/zsh

+ SU_BINARY_SEARCH=("/system/xbin/su" "/system/bin/su")

+ [[ -x /sbin ]]
+ SU_BINARY_SEARCH+=("/sbin/su" "/sbin/bin/su")

+ unset LD_LIBRARY_PATH

+ unset LD_PRELOAD

+ [[ -z '' ]]

++ /sbin/su -v

+ [[ 2aede977:MAGISKSU == *\M\A\G\I\S\K\S\U ]]

+ exec /sbin/su -c 'PATH=/sbin/.magisk/busybox env -i  PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets  LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib:/system/lib64  ANDROID_DATA=/data  TMPDIR=/data/data/com.termux/files/home/.suroot/.tmp  PREFIX=/data/data/com.termux/files/usr  TERM=xterm-256color  LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so  ANDROID_ROOT=/system  HOME=/data/data/com.termux/files/home/.suroot  /data/sdext2/com.termux/files/usr/bin/zsh'`

**Comment by 4eckdat** [comment]
This works with zsh well: 
[tsu.txt](https://github.com/cswl/tsu/files/4605961/tsu.txt)

**Comment by cswl** [comment]
Oh are you using Termux on external sdcard??

**Comment by 4eckdat** [comment]
Yes.
data was moved to external sdcard and the symlink was created:
`cp -Ppr /data/data/com.termux /data/sdext2

rm -r /data/data/com.termux

ln -s /data/sdext2/com.termux /data/data`

**Comment by 4eckdat** [comment]
> Oh are you using Termux on external sdcard??

But I think that discussed issue is not connected with Termux's location, because zsh shell isn't available in tsu mode also on Andnoid x86 system and I didn't transfer Termux from it's original location on this system.

**Comment by huazhaozhe** [comment]
Android10 MIUI12 magisk20.4
```
(tasker)
# u0_a41 @ localhost in ~ [20:35:53]
$
(tasker)
# u0_a41 @ localhost in ~ [20:35:54]
$ tsu --dbg
+ shift
+ _TSU_CALL=tsu
+ [[ tsu == \s\u\d\o ]]
+ TERMUX_FS=/data/data/com.termux/files
+ TERMUX_PREFIX=/data/data/com.termux/files/usr
+ TERMUX_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ ROOT_HOME=/data/data/com.termux/files/home/.suroot
+ ANDROID_SYSPATHS=/system/bin:/system/xbin
+ EXTRA_SYSPATHS=/sbin:/sbin/bin
+ BB_MAGISK=/sbin/.magisk/busybox
+ log_DEBUG TSU_AS_SUDO
+ [[ '' == true ]]
+ log_DEBUG _TSU_AS_SUDO
+ [[ -z '' ]]
+ SWITCH_USER=
+ declare -A EXP_ENV
+ log_DEBUG _TSU_AS_SUDO
+ [[ '' == true ]]
+ root_shell_helper
+ log_DEBUG root_shell_helper
+ [[ -n '' ]]
+ log_DEBUG ALT_SHELL
+ [[ '' == \s\y\s\t\e\m ]]
+ [[ -n '' ]]
+ [[ -x /data/data/com.termux/files/home/.termux/shell ]]
++ readlink -f -- /data/data/com.termux/files/home/.termux/shell
+ ROOT_SHELL=/data/data/com.termux/files/usr/bin/zsh
+ env_path_helper
+ log_DEBUG env_path_helper
+ log_DEBUG SWITCH_USER
+ [[ -z '' ]]
+ [[ -d /data/data/com.termux/files/home/.suroot ]]
+ NEW_HOME=/data/data/com.termux/files/home/.suroot
+ EXP_ENV[PREFIX]=/data/data/com.termux/files/usr
+ EXP_ENV[TMPDIR]=/data/data/com.termux/files/home/.suroot/.tmp
+ EXP_ENV[LD_PRELOAD]=/data/data/com.termux/files/usr/lib/libtermux-exec.so
+ log_DEBUG _TSU_AS_SUDO
+ [[ '' == true ]]
+ NEW_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
+ log_DEBUG LD_LIBRARY_PATH
+ [[ -n '' ]]
+ ASP=/system/bin:/system/xbin:/sbin:/sbin/bin
+ log_DEBUG PREPEND_SYSTEM_PATH
+ [[ -n '' ]]
+ NEW_PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/system/bin:/system/xbin:/sbin:/sbin/bin
+ EXP_ENV[PATH]=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/system/bin:/system/xbin:/sbin:/sbin/bin
+ EXP_ENV[HOME]=/data/data/com.termux/files/home/.suroot
+ EXP_ENV[TERM]=xterm-256color
+ [[ -z true ]]
+ set +x
+ STARTUP_SCRIPT=/data/data/com.termux/files/usr/bin/zsh
+ SU_BINARY_SEARCH=("/system/xbin/su" "/system/bin/su")
+ [[ -x /sbin ]]
+ SU_BINARY_SEARCH+=("/sbin/su" "/sbin/bin/su")
+ unset LD_LIBRARY_PATH
+ unset LD_PRELOAD
+ [[ -z '' ]]
++ /sbin/su -v
+ [[ 20.4:MAGISKSU == *\M\A\G\I\S\K\S\U ]]
+ su_args=("/sbin/su")
+ [[ -z '' ]]
+ su_cmdline='PATH=/sbin/.magisk/busybox '
+ [[ -n '' ]]
+ su_cmdline+='env -i  PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/system/bin:/system/xbin:/sbin:/sbin/bin  ANDROID_DATA=/data  TMPDIR=/data/data/com.termux/files/home/.suroot/.tmp  PREFIX=/data/data/com.termux/files/usr  TERM=xterm-256color  LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so  ANDROID_ROOT=/system  HOME=/data/data/com.termux/files/home/.suroot  /data/data/com.termux/files/usr/bin/zsh'
+ su_args+=("-c")
+ exec /sbin/su -c 'PATH=/sbin/.magisk/busybox env -i  PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:/system/bin:/system/xbin:/sbin:/sbin/bin  ANDROID_DATA=/data  TMPDIR=/data/data/com.termux/files/home/.suroot/.tmp  PREFIX=/data/data/com.termux/files/usr  TERM=xterm-256color  LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so  ANDROID_ROOT=/system  HOME=/data/data/com.termux/files/home/.suroot  /data/data/com.termux/files/usr/bin/zsh'
#
#
```
